public enum State {
    IDLE,
    AWAITING_ADD,
    AWAITING_SET_CHOICE,
    AWAITING_SET_ACTION,
    AWAITING_SET_SEASON,
    AWAITING_SET_EPISODE,
    AWAITING_DELETE_CHOICE,
    AWAITING_RENAME_CHOICE,
    AWAITING_RENAME_INPUT
    }